services:
  # --- Service 1 : Base de données MongoDB ---
  mongodb:
    image: mongo:7
    container_name: workshop-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Service 2 : API Backend NestJS ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop-backend
    restart: always
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/workshopsdb
      - CORS_ORIGIN=http://localhost
      - NODE_ENV=production
    depends_on:
      mongodb:
        condition: service_healthy

# --- Volume persistant pour MongoDB ---
volumes:
  mongo_data:
